### ISSUE TITLE
wrong version in PyPI

### ISSUE THREAD

**Issue by jabbalaci** [Doist/redis_wrap#8]
Hi,

Thanks for this cool wrapper, but the PyPI version is not correct. I just installed it via `pip` and made some tests with the lists. Strangely, when I appended new elements and printed the list, the order was reversed! I checked the source and found this:

    class ListFu:
        ...
        def append(self, item):
            self.conn.lpush(self.name, item)

It should be `rpush`, not `lpush`. The version here on github seems OK.

Thanks,

Laszlo

**Comment by amix** [comment]
1.4.3 is out that should fix this. Sorry :)
