### ISSUE TITLE
problem with slicing

### ISSUE THREAD

**Issue by jabbalaci** [Doist/redis_wrap#9]
I just upgraded to version 1.4.3 and I have a problem with slicing. The following assertion fails:

    def fails():
        get_redis().delete('movies')
        movies = get_list('movies')
        movies.append('hook')
        movies.append('star wars')
        movies.append('indiana jones')

        print movies[:2]
        assert movies[:2] == ['hook', 'star wars']

`movies[:2]` should return the first 2 elements but it returns the first three.

**Comment by amix** [comment]
Please submit a patch

**Comment by jabbalaci** [comment]
But do you agree with that? It should behave just like in plain old Python.

**Comment by amix** [comment]
I do agree :)

**Comment by jabbalaci** [comment]
OK, pull request was sent.

**Comment by jabbalaci** [comment]
close this issue if it was solved
